[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "@neondatabase/serverless", "drizzle-orm"]
  node_bundler = "esbuild"
  included_files = ["server/**", "shared/**"]

# API routes - must come first
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback - must come last
# This ensures all non-API routes are handled by React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200